"""empty message

Revision ID: 90b26f37f2ea
Revises: a5cffa318ac2
Create Date: 2025-08-21 00:42:47.868751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b26f37f2ea'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('privacy', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publicacion_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacion_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('seguidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_seguidor', sa.Integer(), nullable=False),
    sa.Column('id_seguido', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_seguido'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seguidor'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_seguidor', 'id_seguido', name='uix_seguidor_seguido')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pub', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pub'], ['publicacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comentarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_id_pub'), ['id_pub'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('medio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_pub', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_pub'], ['publicacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medio_id_pub'), ['id_pub'], unique=False)
        batch_op.create_index(batch_op.f('ix_medio_id_usuario'), ['id_usuario'], unique=False)

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    with op.batch_alter_table('medio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medio_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_medio_id_pub'))

    op.drop_table('medio')
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_comentarios_id_pub'))
        batch_op.drop_index(batch_op.f('ix_comentarios_created_at'))

    op.drop_table('comentarios')
    op.drop_table('seguidores')
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publicacion_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_publicacion_created_at'))

    op.drop_table('publicacion')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
